### PR TITLE
Resharper base

### PR DESCRIPTION
**Pull request by meh-uk**
Extracting some base classes from ReSharper 6.1.1 and later so we don't have to copy-paste everything for each new version which is creating a bit of a mess.

Also includes the project fixes so they load in Visual Studio from pull request #4.

### CODE REVIEW

**Comment by citizenmatt** [comment]
Thanks for the contribution! I haven't looked at it yet, but just to let you know, I'm expecting to drop support for older ReSharper versions completely. Likely only supporting the latest version - there are already versions for ReSharper 8.2 and below currently available (and 9.0 and 9.1 in pre-release form). So, I don't see much point in keeping anything older than current.

**Comment by meh-uk** [comment]
I personally only really care about R# 9 support, but I'd expect there are lots of people on older versions of R# who might be interested if StyleCop itself is improved. In the past I certainly haven't upgraded R# for every version.

Besides even if you kill backwards compatibility completely for now, you'll need it in the future - and the current approach of copy/pasting a whole bunch of code for each new version of R# you want to support sucks.

**Comment by citizenmatt** [comment]
I hate to do this, but I'm going to decline this PR. I very much agree that the copy/paste approach isn't appropriate, and don't want to follow it. So I'm only going to have one version in the repo (9.2) and that project will get upgraded to 10 when it's available - the 9.2 binary will still be on the extension manager, so it's not an issue to concentrate on a single version. Which means there's now no need for a shared base folder. Sorry!

But thanks for submitting, though, it's **REALLY** cool to get PRs!

**Comment by meh-uk** [comment]
I think given the other more advanced project means this project is largely redundant going forward I think this is best :).

**Pull request closed without merging**
