### PR TITLE
Fix interference with ReSharper extension. (#50)

### LINKED ISSUE #50: TypeLoadException (method not implemented) when starting stylecop
When I have the resharper extension "stylecop by jetbrains" not installed, everything seems to work fine.

When I installed the resharper extension I run the command ClassViewContextMenus ClassViewProject RunStyleCop, it shows me a message box titled StyleCop, with message "An exception occurred while loading one of the styleop addins: System.TypeLoadException, Method 'get_Container' in type 'somegarbledtype' from assembly 'yWorks.yFilesWPF.Viewer, Version=2.4.0.3, Culture=neutral,PublicKeyToke=sometoken'" does not have an implementation.

After uninstalling, the stylecop command runs fine again.

### PR DESCRIPTION
**Pull request by matkoch**
This should fix #50. I couldn't completely build and test the extension, but manipulating while debugging worked okay.

### CODE REVIEW

**Comment by ThielHater** [comment]
@matkoch Did you have problems compiling the StyleCop.VisualStudio project? It references two dll files from the Visual Studio SDK for Visual Studio 2012, as I found out. Would you mind adding @citizenmatt as a reviewer? He seems to be more active lately.

**Comment by TannerBragg** [comment]
Once this fix makes it into master, can @csdahlberg @citizenmatt publish a minor software release to fix the error in VS2017?  This error is quite intrusive.

**Comment by ThatOhio** [comment]
Still seeing this issue, would be awesome if it could be resolved.

**Comment by matkoch** [comment]
Just FYI: https://blog.jetbrains.com/dotnet/2018/04/09/stylecop-code-style-settings-inspections/ Maybe this is of interest.

**Comment by ThatOhio** [comment]
I'll take a look, my current issue is with a separate third party service that I'd like to use that could make use of the standard StyleCop settings, and not resharpers. I can edit how it displays in visual studio, but without a proper StyleCop settings file my third party service will act differently.

**Comment by matkoch** [comment]
@ThatOhio this is using the standard stylecop config.

**Pull request merged**
